import type { components } from './schema'

type Schemas = components['schemas']

export type User = Schemas['UserOut']
export type UserRole = Schemas['UserRole']
export type UserList = Schemas['UserListOut']
export type AdminUserUpdateIn = Schemas['AdminUserUpdateIn']
export type TokenOut = Schemas['TokenOut']
export type LoginIn = Schemas['LoginIn']
export type RegisterIn = Schemas['RegisterIn']
export type ForgotPasswordIn = Schemas['ForgotPasswordIn']
export type ResetPasswordIn = Schemas['ResetPasswordIn']
export type Service = Schemas['ServiceOut']
export type ServiceIn = Schemas['ServiceIn']
export type ServiceUpdateIn = Schemas['ServiceUpdateIn']
export type Provider = Schemas['ProviderOut']
export type Booking = Schemas['BookingOut']
export type BookingIn = Schemas['BookingIn']
export type BookingList = Schemas['BookingListOut']
export type BookingStatus = Schemas['BookingStatus']
export type AvailabilityRule = Schemas['AvailabilityRuleOut']
export type AvailabilityRuleIn = Schemas['AvailabilityRuleIn']
export type TimeOff = Schemas['TimeOffOut']
export type TimeOffIn = Schemas['TimeOffIn']
export type Stats = Schemas['StatsOut']
